//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BiliBilisim_Proje.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class admin
    {
        public int admin_id { get; set; }

        [Required(ErrorMessage = "Kullanýcý Adý Zorunludur")]
        public string kuladi { get; set; }
        [Required(ErrorMessage = "Þifre Zorunludur")]
        public string sifre { get; set; }
    }
}
