//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BiliBilisim_Proje.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class siparisler
    {
        public int kayit_no { get; set; }
        public int sip_no { get; set; }
        public int uye_id { get; set; }
        public int adet { get; set; }
        public System.DateTime a_tarih { get; set; }
        public int urun_id { get; set; }
    
        public virtual urunler urunler { get; set; }
        public virtual uyeler uyeler { get; set; }
    }
}
