//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BiliBilisim_Proje.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class urunler
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public urunler()
        {
            this.siparisler = new HashSet<siparisler>();
        }

        [Required]
        public int urun_id { get; set; }
        [Required(ErrorMessage = "Ürün Adý Giriþi Zorunludur")]
        public string urun_adi { get; set; }
        [Required(ErrorMessage = "Marka Adý Giriþi Zorunludur")]
        public string marka { get; set; }
        [Required(ErrorMessage = "Model Adý Giriþi Zorunludur")]
        public string model { get; set; }
        [Required(ErrorMessage = "Kategori Seçimi Zorunludur")]
        public int kate_no { get; set; }
        [Required(ErrorMessage = "Fiyat Giriþi Zorunludur")]
        public decimal fiyati { get; set; }
        [Required(ErrorMessage = "Stok Giriþi Zorunludur")]
        [Range(0, 99999999, ErrorMessage = "Stok Adedi En Az 0 Olmalýdýr")]
        public int stok { get; set; }
        public string fotolar { get; set; }
        [Required(ErrorMessage = "Satýþ Adedi Giriþi Zorunludur")][Range(0,99999999,ErrorMessage = "Satýþ Adedi En Az 0 Olmalýdýr")]
        public short satis_adet { get; set; }
        [Required(ErrorMessage = "Ürün Açýklama Giriþi Zorunludur")]
        public string urun_aciklama { get; set; }
    
        public virtual kategori kategori { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<siparisler> siparisler { get; set; }
    }
}
