//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BiliBilisim_Proje.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class urunler
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public urunler()
        {
            this.siparisler = new HashSet<siparisler>();
        }
    
        public int urun_id { get; set; }
        public string urun_adi { get; set; }
        public string marka { get; set; }
        public string model { get; set; }
        public int kate_no { get; set; }
        public decimal fiyati { get; set; }
        public int stok { get; set; }
        public string fotolar { get; set; }
        public short satis_adet { get; set; }
    
        public virtual kategori kategori { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<siparisler> siparisler { get; set; }
    }
}
