//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BiliBilisim_Proje.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class uyeler
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public uyeler()
        {
            this.siparisler = new HashSet<siparisler>();
        }
    
        public int uye_id { get; set; }
        public string kuladi { get; set; }
        public string sifre { get; set; }
        public string ad_soyad { get; set; }
        public System.DateTime dog_tar { get; set; }
        public bool cinsiyet { get; set; }
        public bool vip { get; set; }
        public string adres { get; set; }
        public string email { get; set; }
        public int plaka { get; set; }
        public bool vip_basvuru { get; set; }
    
        public virtual sehirler sehirler { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<siparisler> siparisler { get; set; }
    }
}
